name: Build LibVLC for Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
            
      - name: Download LibVLC source code
        run: git clone --depth 1 -b master https://github.com/videolan/vlc

      - name: Copy external dependencies
        run: |
          git clone --depth 1 -b master https://github.com/axiomatic-systems/Bento4
          cp -r Bento4/Source/C++/Core/. newsrc/modules/demux/adaptive/encryption
          cp -r Bento4/Source/C++/Codecs/. newsrc/modules/demux/adaptive/encryption
          cp -r Bento4/Source/C++/Crypto/. newsrc/modules/demux/adaptive/encryption
          cp -r Bento4/Source/C++/MetaData/. newsrc/modules/demux/adaptive/encryption
          
      - name: Copy modified source code to LibVLC
        run: cp -R ${{ github.workspace }}/newsrc/* ${{ github.workspace }}/vlc

      - name: List files
        run: |
          cd vlc/modules/demux/adaptive/encryption
          echo "Listing all files..."
          for FILE in Ap4*; do echo $FILE; done
