name: Build VLC for Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
            
      - name: Download VLC source code
        run: git clone --depth 1 -b master https://github.com/videolan/vlc

      - name: Copy modified source code to VLC folders
        run: cp -R ${{ github.workspace }}/newsrc/* ${{ github.workspace }}/vlc
          
      - name: Install dependencies
        run: |
          sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
          sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream
          sudo apt update
          sudo apt install pipewire pipewire-pulse pipewire-audio-client-libraries wireplumber
          systemctl --user --now enable wireplumber.service
          sudo apt-get build-dep vlc

      - name: Bootstrap VLC
        working-directory: ${{ github.workspace }}/vlc
        run: ./bootstrap

      - name: Create output directory
        run: mkdir vlc-installed
        
      - name: Configure VLC
        working-directory: ${{ github.workspace }}/vlc
        run: >-
          ./configure --disable-sout --disable-lua --disable-vlm --disable-archive --disable-live555 --disable-dc1394 --disable-dv1394 --disable-linsys
          --disable-dvdread --disable-dvdnav --disable-bluray --disable-opencv --disable-smbclient --disable-dsm --disable-sftp --disable-nfs --disable-smb2 --disable-v4l2 --disable-amf-scaler
          --disable-amf-enhancer --disable-amf-frc --disable-decklink --disable-vcd --disable-vnc --disable-freerdp --disable-asdcp --disable-dvbpsi --disable-dvbcsa --disable-gme --disable-sid
          --disable-ogg --disable-shout --disable-matroska --disable-mod --disable-mpc --disable-shine --disable-omxil --disable-rpi-omxil --disable-mad --disable-mpg123 --disable-gst-decode
          --disable-aom --disable-rav1e --disable-dav1d --disable-vpx --disable-twolame --disable-fdkaac --disable-flac --disable-vorbis --disable-tremor --disable-speex --disable-rnnoise --disable-opus
          --disable-theora --disable-oggspots --disable-daala --disable-openapv --disable-bpg --disable-x262 --disable-x265 --disable-x264 --disable-x26410b --disable-davs2 --disable-fluidsynth
          --disable-fluidlite --disable-zvbi --disable-telx --disable-aribcaption --disable-aribsub --disable-aribb25 --disable-kate --disable-tiger --disable-css --disable-xcb --disable-vdpau
          --disable-svg --disable-svgdec --disable-caca --disable-kva --disable-mmal --disable-pulse --disable-alsa --disable-oss --disable-sndio --disable-jack --disable-opensles --disable-soxr
          --disable-kai --disable-chromaprint --disable-chromecast --disable-qt --disable-skins2 --disable-ncurses --disable-lirc --disable-srt --disable-rist --disable-goom --disable-projectm
          --disable-vsxu --disable-avahi --disable-udev --disable-mtp --disable-upnp --disable-microdns --disable-taglib --disable-secret --disable-kwallet --disable-update-check
          --disable-osx-notifications --disable-notify --disable-medialibrary --disable-vlc --prefix=${{ github.workspace }}/vlc-installed

      - name: Compile VLC
        working-directory: ${{ github.workspace }}/vlc
        run: make

      - name: Install VLC
        working-directory: ${{ github.workspace }}/vlc
        run: |
          sudo make install
          sudo ldconfig

      - name: Copy VLC libraries and headers to sample application folder
        run: |
          mkdir sampleapp
          cd sampleapp
          mkdir include
          mkdir lib
          cp -R /usr/local/include/vlc ${{ github.workspace }}/sampleapp/include
          cp /usr/local/lib/libvlc.* ${{ github.workspace }}/sampleapp/lib
          cp /usr/local/lib/libvlccore.* ${{ github.workspace }}/sampleapp/lib
          cp -R /usr/local/lib/vlc ${{ github.workspace }}/sampleapp/lib

      - name: Upload VLC
        uses: actions/upload-artifact@v7
        with:
          name: VLC-Linux
          path: ${{ github.workspace }}/vlc-installed
          if-no-files-found: error
          retention-days: 1
          include-hidden-files: true
